{
 "title": "MSA Blueprint Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Invocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Microservice A invocations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"200\",method=\"GET\",path=\"/api/greeting\"}"
    }
   ]
  },
  {
   "title": "Microservice B invocations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/greeting\",}"
    }
   ]
  },
  {
   "title": "Microservice C invocations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "application:greeting_count" }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Microservice  A - Response Times",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{le=\"10\",status_code=\"200\",method=\"GET\",path=\"/api/greeting\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{le=\"1.5\",status_code=\"200\",method=\"GET\",path=\"/api/greeting\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{le=\"0.3\",status_code=\"200\",method=\"GET\",path=\"/api/greeting\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{le=\"0.1\",status_code=\"200\",method=\"GET\",path=\"/api/greeting\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{le=\"0.03\",status_code=\"200\",method=\"GET\",path=\"/api/greeting\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{le=\"0.003\",status_code=\"200\",method=\"GET\",path=\"/api/greeting\"}",
     "legendFormat": "less than {{le}}"
    }
   ]
  },
  {
   "title": "Microservice B - Response Times",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/greeting\",} / http_server_requests_seconds_count{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/greeting\",}",
     "legendFormat": "Mean response time"
    }
   ]
  },
  {
   "title": "Microservice C - Response Times",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:greeting_time_mean_seconds",
     "legendFormat": "Mean response time"
    },
    {
     "expr": "application:greeting_time_max_seconds",
     "legendFormat": "Max response time"
    }
   ]
  },
  { "title": "JVM insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Microservice B JVM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"microservice-b\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Microservice C JVM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:memory_pool_ps_eden_space_usage_bytes",
     "legendFormat": "PS Eden"
    },
    {
     "expr": "vendor:memory_pool_ps_old_gen_usage_bytes",
     "legendFormat": "PS Old Gen"
    },
    {
     "expr": "vendor:memory_pool_ps_survivor_space_usage_bytes",
     "legendFormat": "PS Survivor"
    }
   ]
  }
 ]
}