# This properties file should be used to initialise a ConfigMap
greeting:
  message: "Bonjour %s from a ConfigMap!"

# Metrics related configurations
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# OpenTracing related configurations.
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    enable-b3-propagation: false
    udp-sender:
      host: "jaegerhost"
      port: 5775
