
# If OpenShift ConfigMap wasn't deployed and application is running locally, we can set greeting.message here.
greeting:
  message: "Hello, %s!"

# Metrics related configurations
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# OpenTracing related configurations.
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    enable-b3-propagation: false
    udp-sender:
      host: "localhost"
      port: 5775
